In [3]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# ***Task 1***

In [4]:

# Input the last two digits of your student ID
d1 = int(input("Enter the last digit of your student ID (d1): "))
d2 = int(input("Enter the second last digit of your student ID (d2): "))

# Create the matrix
A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

# Display the matrix
print("\nMatrix A:")
print(A)

Enter the last digit of your student ID (d1): 0
Enter the second last digit of your student ID (d2): 1

Matrix A:
[[2 2]
 [0 3]]


# ***Task 2***

In [5]:
# Example matrix A
A = np.array([[2, 2], [0, 3]])

# 1. Shape of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)


# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix

# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix

# 4. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0


# 5. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors



# Display results
print("Shape of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)



Shape of A: (2, 2)
Determinant of A: 6.0
Inverse of A:
 [[ 0.5        -0.33333333]
 [ 0.          0.33333333]]
Rank of A: 2
Eigenvalues of A: [2. 3.]
Eigenvectors of A:
 [[1.         0.89442719]
 [0.         0.4472136 ]]


# Task **3**

In [6]:
B = A.copy()

# Changing exactly one value: Adding +1 to row 1, col 1 (A[0, 0])
row_idx, col_idx = 0, 0
B[row_idx, col_idx] += 1


print(
    f"Changed Element: Row {row_idx + 1}, Column {col_idx + 1} "
    f"(Value changed from {A[row_idx, col_idx]} to {B[row_idx, col_idx]})"
)
print("Matrix B =\n", B)

Changed Element: Row 1, Column 1 (Value changed from 2 to 3)
Matrix B =
 [[3 2]
 [0 3]]


# **Task 4**

In [7]:
# Example matrix A
A = np.array([[3, 2], [0, 3]])

# 1. Shape of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)


# 2. Determinant of a matrix
det_A = np.linalg.det(A)  # Returns the determinant of the matrix

# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)  # Returns the rank of the matrix

# 4. Inverse of a matrix
if np.linalg.det(A) != 0:  # Check if matrix is invertible
    inv_A = np.linalg.inv(A)  # Compute the inverse of A
else:
    inv_A = "Matrix is singular, cannot compute inverse"  # No inverse if determinant is 0


# 5. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors



# Display results
print("Shape of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Shape of A: (2, 2)
Determinant of A: 9.000000000000002
Inverse of A:
 [[ 0.33333333 -0.22222222]
 [ 0.          0.33333333]]
Rank of A: 2
Eigenvalues of A: [3. 3.]
Eigenvectors of A:
 [[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  3.33066907e-16]]


# Task 5

Here are the step-by-step answers to **Question 5 (Comparison & Explanation)** written in plain text, tailored to experiment:


### **Question 1: How did the determinant change and why?**

* **Answer:**
The determinant changed from its initial value in **A** to a new value in **B** (for example, if $\det(A) = -12$ and adding $+1$ to entry $(0,0)$ changes it, the new determinant becomes $\det(B) = 0$).
* **Why:**
By **Laplace (Cofactor) Expansion**, modifying a single entry $A_{i,j}$ by adding $+1$ changes the determinant by the **cofactor** $C_{i,j}$ corresponding to that position:

$$\det(B) = \det(A) + (+1) \cdot C_{i,j}$$



Since $C_{i,j} = (-1)^{i+j} M_{i,j}$ (where $M_{i,j}$ is the sub-determinant formed by removing row $i$ and column $j$), the determinant shifts by exactly the value of that cofactor.




### **Question 2: Did the rank change? Explain.**

* **Answer:**
* **If both $\det(A) \neq 0$ and $\det(B) \neq 0$:** The rank **did not change** (it remained $3$).
* **If $\det(B)$ became $0$:** The rank **decreased** from $3$ to $2$.


* **Explanation:**
The rank of an $n \times n$ matrix represents the maximum number of linearly independent rows or columns. As long as a matrix has a non-zero determinant, it has **full rank** ($3$). Changing a single element only alters the rank if it introduces a linear dependency between rows/columns (which makes the determinant zero) or breaks an existing linear dependency.





### **Question 3: How did the eigenvalues respond to the value change?**

* **Answer:**
The eigenvalues shifted across the spectrum, and their sum increased by $+1$ (if a diagonal element was changed).
* **Explanation:**
1. **Trace Property:** The sum of all eigenvalues of a matrix is equal to its **trace** (the sum of its diagonal elements):

$$\sum \lambda_i = \text{trace}(M)$$



If $+1$ was added to a **diagonal element**, the trace increased by $+1$, causing the sum of the eigenvalues to increase by $+1$.
2. **Gerschgorin Circle Theorem:** Modifying a matrix entry continuously shifts its eigenvalue spectrum in the complex plane according to matrix perturbation theory.





### **Question 4: Is B easier or harder to invert than A? Why?**

* **Answer:**
* **If $\det(B) = 0$:** Matrix **B cannot be inverted at all** because it is singular.
* **If $\det(B) \neq 0$:** Compare the **Condition Numbers** $\kappa(M) = \Vert{}M\Vert{} \cdot \Vert{}M^{-1}\Vert{}$:
* If $\kappa(B) < \kappa(A)$, matrix **B is easier (more numerically stable)** to invert.
* If $\kappa(B) > \kappa(A)$, matrix **B is harder (less stable)** to invert.




* **Why:**
In numerical linear algebra, the difficulty and numerical stability of matrix inversion depend on the **condition number**. A matrix with a condition number closer to $1$ is better-conditioned (easier to invert without rounding errors), while a matrix with a high condition number (or a determinant close to $0$) is ill-conditioned and harder to invert accurately.