In [1]:
import numpy as np

# Sample 2x3 matrix with floating-point numbers
matrix = np.array([ [3.5, 1.2, 4.8],[1.1, 5.9, 2.4]])

# 1. Maximum value and index of max element
max_value = np.max(matrix)
max_index_flat = np.argmax(matrix)                # Flat index
max_index_2d = np.unravel_index(max_index_flat, matrix.shape) # (row, col) tuple

# 2. Minimum value and index of min element
min_value = np.min(matrix)
min_index_flat = np.argmin(matrix)                # Flat index
min_index_2d = np.unravel_index(min_index_flat, matrix.shape) # (row, col) tuple

# 3. Size / Length of the matrix
total_elements = matrix.size                      # Total elements in matrix (6)
num_rows = len(matrix)                            # Number of rows (2)

# 4. Sorting Options

# A. Ascending sort along rows (default axis=-1)
sorted_rows_asc = np.sort(matrix, axis=1)

# B. Descending sort WITHIN ROWS
sorted_rows_desc = -np.sort(-matrix, axis=1)      # Or np.sort(matrix, axis=1)[:, ::-1]

# C. Descending sort across the TOTAL MATRIX (flattened into 1D)
sorted_total_desc = np.sort(matrix, axis=None)[::-1]

# D. Descending sort across TOTAL MATRIX (reshaped back to 2x3)
sorted_matrix_desc = sorted_total_desc.reshape(matrix.shape)

# 5. Statistical Aggregations
sum_values = np.sum(matrix)
prod_values = np.prod(matrix)
median_value = np.median(matrix)
mean_value = np.mean(matrix)
std_dev = np.std(matrix)

# Display results
print("Original Matrix:\n", matrix)
print("\nMax value:", max_value, "at 2D index", max_index_2d)
print("Min value:", min_value, "at 2D index", min_index_2d)
print("Total elements:", total_elements)
print("\n--- Sorting ---")
print("1. Sorted within rows (Ascending):\n", sorted_rows_asc)
print("2. Sorted within rows (Descending):\n", sorted_rows_desc)
print("3. Total matrix sorted (Descending 1D):", sorted_total_desc)
print("4. Total matrix sorted (Descending 2x3):\n", sorted_matrix_desc)
print("\n--- Statistics ---")
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Original Matrix:
 [[3.5 1.2 4.8]
 [1.1 5.9 2.4]]

Max value: 5.9 at 2D index (np.int64(1), np.int64(1))
Min value: 1.1 at 2D index (np.int64(1), np.int64(0))
Total elements: 6

--- Sorting ---
1. Sorted within rows (Ascending):
 [[1.2 3.5 4.8]
 [1.1 2.4 5.9]]
2. Sorted within rows (Descending):
 [[4.8 3.5 1.2]
 [5.9 2.4 1.1]]
3. Total matrix sorted (Descending 1D): [5.9 4.8 3.5 2.4 1.2 1.1]
4. Total matrix sorted (Descending 2x3):
 [[5.9 4.8 3.5]
 [2.4 1.2 1.1]]

--- Statistics ---
Sum of elements: 18.9
Product of elements: 314.01216
Median value: 2.95
Mean value: 3.15
Standard deviation: 1.778341924377874
